version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: giggo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: giggo
      POSTGRES_PASSWORD: giggo123
      POSTGRES_DB: giggo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: giggo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@giggo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
